name: karios
channels:
  - conda-forge
dependencies:
  # - python=3.11
  - pip
  - matplotlib-base=3.9.*

  - gdal=3.8.1
  - opencv=4.8.1
  - pandas=2.1.4
  - python=3.12
  - scikit-image=0.22.0
  - rich-click=1.8.9
