name: Ubuntu Tests

on:
  push:
    branches: [ '**' ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'LICENSE'
      - 'NOTICE'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'LICENSE'
      - 'NOTICE'
      - 'CHANGELOG.md'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: 'latest'
        channels: conda-forge
        channel-priority: strict
        environment-file: environment.yml
        activate-environment: karios

    - name: Test conda installation
      shell: bash -l {0}
      run: conda info

    # - name: Install dependencies manually using conda install
    #   shell: bash -l {0}
    #   run: |
    #     conda install --yes \
    #       numpy=1.26.* \
    #       matplotlib-base=3.9.* \
    #       gdal=3.8.1 \
    #       opencv=4.8.1 \
    #       pandas=2.1.4 \
    #       python=3.12 \
    #       scikit-image=0.22.0 \
    #       rich-click=1.8.9

    - name: Install package in development mode
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools>=77.0
        pip install -e .

    - name: Install dev dependencies for testing
      shell: bash -l {0}
      run: |
        pip install pytest
        if [ -f requirements_dev.txt ]; then
          pip install -r requirements_dev.txt

          # conda install -n karios -c conda-forge --file requirements_dev.txt
        fi

    - name: Run tests
      shell: bash -l {0}
      continue-on-error: true
      run: |
        python -m pytest tests/ -v